os: osx
sudo: false
language: node_js
node_js: '9'
cache:
  directories:
  - electron/node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/.npm/_prebuilds"
before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
    export PATH="/tmp/git-lfs:$PATH"
  fi
install:
- yarn
before_script:
- git lfs pull
script:
- if [[ "$TRAVIS_BRANCH" == "refactor" ]]; then cd refactor && npm test && cd ..; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd electron && yarn; fi
- buildver="$(grep version electron/package.json |sed "s/[^0-9.]//g").$(git log --format=%h -1)"
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd electron && yarn && electron-builder -p never --em.version=$buildver; fi
addons:
  artifacts:
    working_dir: dist
    paths:
    - $(git ls-files -o dist/{*.dmg,*.exe,*.deb} | tr "\n" ":")
    target_paths:
    - "/app/build-${TRAVIS_BUILD_NUMBER}_commit-${TRAVIS_COMMIT:0:7}$([ ! -z ${TRAVIS_TAG}] && echo _tag-${TRAVIS_TAG})"
    - DART-Prototype/DART-$buildver.dmg
    bucket: aptrust.public.download
    key: $AWS_ACCESS_KEY_ID
    secret:
      secure: jO8AakBnlOk2xtNk1UOQCzW4dsrELMvlxZufB2KslmxVEfsOk72ymj0jQBE4iPu55LgFzOF3ur/peurPobsDvP70V+w0GUCiE/XwNdIK4zkdZu3KCok3tznKGSiFgMX+1uiBKhDqZ7e85naBjxI2u+VQyWTPt2BEmMykKhg1tv4hYFv+CLOU4cVnoSkTEktbz8RKjMSgIEc6tt2UCZy2OXjoyIcrmnEcCJOJVzg0M7lCBSqwcvXmsoJ+Y+GaoNZg3mQqRFqv1r7E4PfV4HpjJDKjJ024wZqKxkmM59qJeLJBz37JzbAmuI18AGnkx2E/TMKZdOpcy9WmL4WRsprZuEjx+b5G0evY008dD+gR9Cs7mDipTD8K53C0ztnYMZYVj6Xt6J7jLugPvKmnr3XFeAT49k9K8pDMAM7Q/Sf+GKCUXkcWmnPPzoe6k9LN5ks1ZIcpvsR4GEQv0K08EDc/rCdnbKAwUgXBDF0ejt0dTLOqNC6MNn7pVqEVCjmhrPdkAWrwnR+Pdahb+AC87qKM4r5VBIIl7Qro9eDtcfep0cEkvc3mCxpYwo+cTqjPI1SarJjt8xO+AapAurG0ppdZhTx9fGVd0UY9Q6jI0TWds5H1c94NqvEed5pA2xCHK97JbhsrDy0rTm6d6PPTSTv5pCaY9+UZTtRuWcMDVo9kJeA=
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: jO8AakBnlOk2xtNk1UOQCzW4dsrELMvlxZufB2KslmxVEfsOk72ymj0jQBE4iPu55LgFzOF3ur/peurPobsDvP70V+w0GUCiE/XwNdIK4zkdZu3KCok3tznKGSiFgMX+1uiBKhDqZ7e85naBjxI2u+VQyWTPt2BEmMykKhg1tv4hYFv+CLOU4cVnoSkTEktbz8RKjMSgIEc6tt2UCZy2OXjoyIcrmnEcCJOJVzg0M7lCBSqwcvXmsoJ+Y+GaoNZg3mQqRFqv1r7E4PfV4HpjJDKjJ024wZqKxkmM59qJeLJBz37JzbAmuI18AGnkx2E/TMKZdOpcy9WmL4WRsprZuEjx+b5G0evY008dD+gR9Cs7mDipTD8K53C0ztnYMZYVj6Xt6J7jLugPvKmnr3XFeAT49k9K8pDMAM7Q/Sf+GKCUXkcWmnPPzoe6k9LN5ks1ZIcpvsR4GEQv0K08EDc/rCdnbKAwUgXBDF0ejt0dTLOqNC6MNn7pVqEVCjmhrPdkAWrwnR+Pdahb+AC87qKM4r5VBIIl7Qro9eDtcfep0cEkvc3mCxpYwo+cTqjPI1SarJjt8xO+AapAurG0ppdZhTx9fGVd0UY9Q6jI0TWds5H1c94NqvEed5pA2xCHK97JbhsrDy0rTm6d6PPTSTv5pCaY9+UZTtRuWcMDVo9kJeA=
  bucket: aptrust.public.download
  local-dir: dist
  upload-dir: DART-Prototype
  acl: public_read
  skip_cleanup: yes
  on:
    repo: APTrust/dart-prototype
notifications:
  slack:
    secure: fYGIkZMYp/HhRhi4/6Q1jpv0nWfpZaqaIKRhhloi+kBIt2fFun49LmTQfjqGLfwKKCKNmx8XzdIASUZuW7auJhHLUZPWaeEDxQjNVjrSOKOUuFUeGCKRJtw6+la0VxT79y5YIWxrnY2Noi8I6NvxniAJwnyQlHdyCnavmZzTA2xQGHxfTI4PR3ZkFt6lVAEC09NZMYwUf5+jsFmR6k/NGBU0jotDkfsm7AdzADSHwqfGvi70V9+muG4DIJejRVOkyCka2EOixbAyOOzbvrDwOo8tZVbY6Ch0LCfYndbDIztWXWb34R8LQEVKJA6QV2qMHmqSyMmR1RUO/OmMDmq+kM4C3M3D91knrugFVJiLJeowj8cb5LKgX35cd8/dHCDnLkSuaAw+rk5ny3TzfX2uh/EI9QN8y7S+er+QNvumy3M1+pkT+M+7t+auu0l7Ab+G/8W5X0PrZaQ+M933tYy1FC0zrp+CNs6BQnVvpql7REISJuuZ3T950FCxLM09XDGTnqxkgo8NrunuHcFgr8Jo74dl4TiixJteCVTOYI46KvfWDDlByKRmYb8GpQOXY4TT0dH5eEOjbcF3OFSQrx0aiC2TA6sTVHzvRqHdjjDGv2IXcJUJyLMnXrUsMVl4MuDCWGsqwKSEh71mflkreSc4yZ17M5ZEUBh90/dA9eICk9c=
