os: osx
sudo: false
language: node_js
node_js: '9'
cache:
  directories:
  - electron/node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/.npm/_prebuilds"
before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
    export PATH="/tmp/git-lfs:$PATH"
  fi
install:
- yarn
before_script:
- git lfs pull
script:
- if [[ "$TRAVIS_BRANCH" == "refactor" ]]; then cd refactor && npm test && cd ..;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd electron && yarn; fi
- buildver="$(grep version electron/package.json |sed "s/[^0-9.]//g").$(git log --format=%h
  -1)"
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd electron && yarn && electron-builder
  -p never --em.version=$buildver; fi
addons:
  artifacts:
    working_dir: dist
    paths:
    - $(git ls-files -o dist/{*.dmg,*.exe,*.deb} | tr "\n" ":")
    target_paths:
    - "/app/build-${TRAVIS_BUILD_NUMBER}_commit-${TRAVIS_COMMIT:0:7}$([ ! -z ${TRAVIS_TAG}
      ] && echo _tag-${TRAVIS_TAG})"
    - DART-Prototype/DART-$buildver.dmg
    bucket: aptrust.public.download
    key:
        secure: "biMU/WdkBL+1o1L2jPZCEhgo3PMfnBdO/g5OPVKwR1skeGxU22o0e0rW/iGucMbmhpFWZUz/l8pVHAGJslT23nMkx2e3+O4JQEteGWTb5rj9R8cNT2zrZnXyXTQ71OEus0PgX0WQ4YfnxyPGupSaPSPP4o/hY4VxAAxmAUXaocyuGPOXHGPUkrceMyD/Nq65WRKqptHR1kO9PCuv/4CLnNKITmpl11e/AvkCug7xbFF0gGeghzYtZ4qNodaFE208ziuzQLEjOp2Et28nGc1K7Qdxtv755r/gjWNHpq5/ccJmiTghFTynCcih9A8z1M8YXcHq5tDHODrxBfqAcY7+6/Y5pKby7nPPBL/wJ2Fp94lOE3eu1tpPeaYP3THKkWwKo6qnnI64HlF57atdY4JwlCVkGlUA3iHpJf66sJMWKcyfj7O10b56DaKIU1OKwd6UJJvzntXNVOjg6/gXffl2IF8GbhwY2YRb1rDki7hmp3Pm8maHiWJmRZ5LvMxZJDL9tY6zMKqiKd9jNgKP5bk46AG/anpGuLaJp2UzkyCGXlD93s22qpiSpN0vmFCwIEhrPJFVaHjShELmcAyTRqcR3BGAULYu8Lb6LJnnwqtcsw3TI/YS4y3ly7wBOtwVYnm4nc4TStfBJJGj13dIbvrCgterWK2d8IDvkPjuXLBilAs="
    secret:
        secure: "oYUjQj5QpCafr9fGZ/NRgh/9/xgFCXL2DCuCIDMhFwhR1BYzCH5aLIeQR0xgXAg30nQ1ClZz/y88IicvNVfGnqVQ8MmfdFQ3bC23u1xFfuzItfRlKeEjL8K6QUsTUTGUMqWDH/rXo7gB0JtCvXTQ4tlN+QwM3h1oUFin/67X90EHrkiGlUfWCtnsK5Wgx1Zt6g1VZT72CR2YE5dChv/mEnle2GhqYrb/bS3ZlmHJvhEgHCmNCfuoSFV8zrCX5cOzlKU7TmmvHc9trqeickpPoCIHZE1RKzl+nkcC/XXJvcezh6yZMGPPgx2Q37S23+5hntgFbVRpXGUIzZFhIbqU5/H8sbWc+xaE3NLQUSbI+1/JHFR6CWbBGOIWTDrmJwkmefc8rkTSn5Hnor3ozxMEqgDM+9QxTqBxMkmjHcMmOIeaz41Qtku5pKhpwpUS7aqqxs9l1RTDII/jsu8hqLPpPfijB2XOHh5ufW2Hs89GjaBtn2zg0wQhKlMhvv91nVLuqyKFGe2F/0zW7Rpk9GX1XaM/AQdYbgodzgxTRvjoaC3IN75/fLbuIpBZjlRSzpBQzUXO2mBii3JI8K48guhHYTWSszDC1hD487UqezFHzwU3hHYcYjftUFyEZ0zPfbyg77b7gkMlI+EWQN6Tnt6PKA4vqskyKh/Hh48riEiWUd4="
deploy:
  provider: s3
  access_key_id:
    secure: "biMU/WdkBL+1o1L2jPZCEhgo3PMfnBdO/g5OPVKwR1skeGxU22o0e0rW/iGucMbmhpFWZUz/l8pVHAGJslT23nMkx2e3+O4JQEteGWTb5rj9R8cNT2zrZnXyXTQ71OEus0PgX0WQ4YfnxyPGupSaPSPP4o/hY4VxAAxmAUXaocyuGPOXHGPUkrceMyD/Nq65WRKqptHR1kO9PCuv/4CLnNKITmpl11e/AvkCug7xbFF0gGeghzYtZ4qNodaFE208ziuzQLEjOp2Et28nGc1K7Qdxtv755r/gjWNHpq5/ccJmiTghFTynCcih9A8z1M8YXcHq5tDHODrxBfqAcY7+6/Y5pKby7nPPBL/wJ2Fp94lOE3eu1tpPeaYP3THKkWwKo6qnnI64HlF57atdY4JwlCVkGlUA3iHpJf66sJMWKcyfj7O10b56DaKIU1OKwd6UJJvzntXNVOjg6/gXffl2IF8GbhwY2YRb1rDki7hmp3Pm8maHiWJmRZ5LvMxZJDL9tY6zMKqiKd9jNgKP5bk46AG/anpGuLaJp2UzkyCGXlD93s22qpiSpN0vmFCwIEhrPJFVaHjShELmcAyTRqcR3BGAULYu8Lb6LJnnwqtcsw3TI/YS4y3ly7wBOtwVYnm4nc4TStfBJJGj13dIbvrCgterWK2d8IDvkPjuXLBilAs="
  secret_access_key:
    secure: "oYUjQj5QpCafr9fGZ/NRgh/9/xgFCXL2DCuCIDMhFwhR1BYzCH5aLIeQR0xgXAg30nQ1ClZz/y88IicvNVfGnqVQ8MmfdFQ3bC23u1xFfuzItfRlKeEjL8K6QUsTUTGUMqWDH/rXo7gB0JtCvXTQ4tlN+QwM3h1oUFin/67X90EHrkiGlUfWCtnsK5Wgx1Zt6g1VZT72CR2YE5dChv/mEnle2GhqYrb/bS3ZlmHJvhEgHCmNCfuoSFV8zrCX5cOzlKU7TmmvHc9trqeickpPoCIHZE1RKzl+nkcC/XXJvcezh6yZMGPPgx2Q37S23+5hntgFbVRpXGUIzZFhIbqU5/H8sbWc+xaE3NLQUSbI+1/JHFR6CWbBGOIWTDrmJwkmefc8rkTSn5Hnor3ozxMEqgDM+9QxTqBxMkmjHcMmOIeaz41Qtku5pKhpwpUS7aqqxs9l1RTDII/jsu8hqLPpPfijB2XOHh5ufW2Hs89GjaBtn2zg0wQhKlMhvv91nVLuqyKFGe2F/0zW7Rpk9GX1XaM/AQdYbgodzgxTRvjoaC3IN75/fLbuIpBZjlRSzpBQzUXO2mBii3JI8K48guhHYTWSszDC1hD487UqezFHzwU3hHYcYjftUFyEZ0zPfbyg77b7gkMlI+EWQN6Tnt6PKA4vqskyKh/Hh48riEiWUd4="

  bucket: aptrust.public.download
  local-dir: dist
  upload-dir: DART-Prototype
  acl: public_read
  skip_cleanup: true
  on:
    repo: APTrust/dart-prototype
notifications:
  slack:
    secure: fYGIkZMYp/HhRhi4/6Q1jpv0nWfpZaqaIKRhhloi+kBIt2fFun49LmTQfjqGLfwKKCKNmx8XzdIASUZuW7auJhHLUZPWaeEDxQjNVjrSOKOUuFUeGCKRJtw6+la0VxT79y5YIWxrnY2Noi8I6NvxniAJwnyQlHdyCnavmZzTA2xQGHxfTI4PR3ZkFt6lVAEC09NZMYwUf5+jsFmR6k/NGBU0jotDkfsm7AdzADSHwqfGvi70V9+muG4DIJejRVOkyCka2EOixbAyOOzbvrDwOo8tZVbY6Ch0LCfYndbDIztWXWb34R8LQEVKJA6QV2qMHmqSyMmR1RUO/OmMDmq+kM4C3M3D91knrugFVJiLJeowj8cb5LKgX35cd8/dHCDnLkSuaAw+rk5ny3TzfX2uh/EI9QN8y7S+er+QNvumy3M1+pkT+M+7t+auu0l7Ab+G/8W5X0PrZaQ+M933tYy1FC0zrp+CNs6BQnVvpql7REISJuuZ3T950FCxLM09XDGTnqxkgo8NrunuHcFgr8Jo74dl4TiixJteCVTOYI46KvfWDDlByKRmYb8GpQOXY4TT0dH5eEOjbcF3OFSQrx0aiC2TA6sTVHzvRqHdjjDGv2IXcJUJyLMnXrUsMVl4MuDCWGsqwKSEh71mflkreSc4yZ17M5ZEUBh90/dA9eICk9c=
